sei_dbt:
  outputs:
    dev:
      type: duckdb
      path: "bcstats_db_dev.duckdb"
      threads: 1

    prod:
      type: duckdb
      path: "bcstats_db_prod.duckdb"
      threads: 4

    test:
      type: duckdb
      path: "bcstats_db_test.duckdb"
      threads: 4

  target: dev
